# ベースイメージ
FROM public.ecr.aws/lambda/python:3.13

# uv インストール
COPY --from=ghcr.io/astral-sh/uv:0.8.13 /uv /uvx /usr/local/bin/

# 依存関係のインストールとコードのコピー
WORKDIR /app
COPY app/${SERVICE}/pyproject.toml app/${SERVICE}/uv.lock ./
RUN uv sync --locked
COPY app/common/ /app/common/
COPY app/${SERVICE}/ /app/${SERVICE}/

# Pythonパスの設定
# これにより、/appにあるモジュールを正しくインポートできる
ENV PYTHONPATH=./

# コンテナ起動時にLambdaハンドラ関数を直接指定
# これがLambdaランタイムが期待する形式
CMD ["${SERVICE}.main.main.lambda_handler"]