name: Check AWS Connection

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  check-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # IAMロールのARNを指定
          role-to-assume: arn:aws:iam::196927155234:role/github-actions-assume-role
          aws-region: ap-northeast-1

      - name: Verify AWS CLI is working
        run: |
          echo "AWSへの接続を確認..."
          aws sts get-caller-identity
          echo "接続成功！"
