name: Build & Deploy Register Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'app/register/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/register/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ap-northeast-1
  GITHUB_AWS_ASSUME_ROLE: github-actions-assume-role
  LAMBDA__FUNCTION_NAME: irir-register-pr
  EVENT_BRIDGE__EVENT_RULE_NAME: register-pr-schedule      # EventBridge ルール名を env で管理
  EVENT_BRIDGE__LAMBDA_PERMISSION_ID: register-pr-schedule-permission  # statement-id
  SERVICE__NAME: register
  DYNAMODB__TABLE_NAME: edinet-document_list-api # no use
  S3__BUCKET_NAME: irir-project # no use
  SECRET_MANAGER__EDINET_API_KEY: EdinetApiKey # no use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.GITHUB_AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      # ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image
        id: build
        run: |
          # 環境変数をシェルで設定
          export SERVICE__NAME=${{ env.SERVICE__NAME }}
          envsubst '$SERVICE__NAME' < Dockerfile.tmpl > Dockerfile

          IMAGE_URI=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/irir/${{ env.SERVICE__NAME }}-pr:latest
          docker build -t $IMAGE_URI -f Dockerfile .

          rm Dockerfile.tmpl

          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_OUTPUT

      # Lambda デプロイ
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA__FUNCTION_NAME }} \
            --image-uri ${{ steps.build.outputs.IMAGE_URI }}


      # Lambdaの実行ロールに権限を付与
      # - name: Attach IAM policy to Lambda role
      #   id: attach_policy
      #   run: |
      #     LAMBDA_ROLE_ARN=$(aws lambda get-function-configuration --function-name ${{ env.LAMBDA__FUNCTION_NAME }} --query 'Role' --output text)
      #     ROLE_NAME=$(echo "${LAMBDA_ROLE_ARN}" | cut -d'/' -f2)
      #     POLICY_ARN="arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:policy/irir-register-lambda-policy" # 先ほど作成したポリシーのARN
      #     aws iam attach-role-policy --role-name $ROLE_NAME --policy-arn $POLICY_ARN

      # EventBridge で Lambda 定期実行登録
      - name: Create EventBridge Rule for Lambda
        run: |
          aws events put-rule \
            --name ${{ env.EVENT_BRIDGE__EVENT_RULE_NAME }} \
            --schedule-expression "cron(0 0 * * ? *)" \
            --state ENABLED

          LAMBDA_ARN=$(aws lambda get-function --function-name ${{ env.LAMBDA__FUNCTION_NAME }} --query 'Configuration.FunctionArn' --output text)
          aws events put-targets \
            --rule ${{ env.EVENT_BRIDGE__EVENT_RULE_NAME }} \
            --targets "Id"="1","Arn"="$LAMBDA_ARN"

          # 既存の権限がある場合は削除
          if aws lambda get-policy --function-name ${{ env.LAMBDA__FUNCTION_NAME }} | grep -q ${{ env.EVENT_BRIDGE__LAMBDA_PERMISSION_ID }}; then
            aws lambda remove-permission \
              --function-name ${{ env.LAMBDA__FUNCTION_NAME }} \
              --statement-id ${{ env.EVENT_BRIDGE__LAMBDA_PERMISSION_ID }}
          fi

          # Lambda 呼び出し権限を追加
          aws lambda add-permission \
            --function-name ${{ env.LAMBDA__FUNCTION_NAME }} \
            --statement-id ${{ env.EVENT_BRIDGE__LAMBDA_PERMISSION_ID }} \
            --action "lambda:InvokeFunction" \
            --principal events.amazonaws.com \
            --source-arn "arn:aws:events:${{ env.AWS_REGION }}:${{ env.AWS_ACCOUNT_ID }}:rule/${{ env.EVENT_BRIDGE__EVENT_RULE_NAME }}"

